fix: make sure lower is never called on None object
The endpoint in the endpoint check can be None which results in
"AttributeError: 'NoneType' object has no attribute 'lower'".