fix call to shutil#move on Python 3.8
tmp_path = PosixPath('/var/lib/jenkins/workspace/enEO_openeo-python-driver_PR-320/pytest-tmp/pytest-of-jenkins/pytest-0/test_disk_workspace_remove_ori1')
remove_original = True

    @pytest.mark.parametrize("remove_original", [False, True])
    def test_disk_workspace_remove_original(tmp_path, remove_original):
        source_directory = tmp_path / "src"
        source_directory.mkdir()
        source_file = source_directory / "file"
        source_file.touch()

        merge = "."
        target_directory = tmp_path / merge

        workspace = DiskWorkspace(root_directory=tmp_path)
>       workspace.import_file(source_file, merge=merge, remove_original=remove_original)

tests/test_workspace.py:43:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
openeo_driver/workspace.py:35: in import_file
    operation(file, target_directory)
/usr/lib64/python3.8/shutil.py:776: in move
    real_dst = os.path.join(dst, _basename(src))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path = PosixPath('/var/lib/jenkins/workspace/enEO_openeo-python-driver_PR-320/pytest-tmp/pytest-of-jenkins/pytest-0/test_disk_workspace_remove_ori1/src/file')

    def _basename(path):
        # A basename() variant which first strips the trailing slash, if present.
        # Thus we always get the last component of the path, even for directories.
        sep = os.path.sep + (os.path.altsep or '')
>       return os.path.basename(path.rstrip(sep))
E       AttributeError: 'PosixPath' object has no attribute 'rstrip'

/usr/lib64/python3.8/shutil.py:740: AttributeError

https://github.com/Open-EO/openeo-geopyspark-driver/issues/883