EP-3965: support aggregate_spatial for spatial cubes in batch jobs
NotImplementedError: unsupported result type <class 'openeo_driver.save_result.AggregatePolygonSpatialResult'>
also: make it explicit that we expect exactly one CSV file